SIN-I13
Sinamecc/sinamecc-wui pull request #72
Opened 2024-11-25 21:42 UTC by frodo-cs

# Summary

Updated the project from Angular 9 to Angular 19, ensuring compatibility and improving performance by modernizing dependencies.

## Description

- Upgraded all Angular packages to version 19.
- Updated all relevant dev dependencies to their latest versions to maintain compatibility.
- Verified and tested the application to ensure no breaking changes were introduced during the upgrade.

## Type of change

- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Evidence:

See [package.json](https://github.com/Sinamecc/sinamecc-wui/blob/262479871eaafb7410b3e614834e86e5212c14a1/package.json)

## Notes

- **User Interface:** The UI must be thoroughly reviewed. There may be bugs, both visual and functional, caused by the migration.
- **Hot Module Replacement (HMR):** HMR is currently non-functional and requires debugging.
- **Corporate Proxy:** The corporate proxy was replaced with a JSON configuration file due to compatibility issues. This workaround must be reviewed for feasibility and proper functionality.

2024-12-11 17:55 UTC, naybort approved these changes

2024-12-11 20:15 UTC, Izcarmt95 approved these changes

2024-12-11 20:19 UTC, Izcarmt95 requested changes
Please upgrade the node version in the Dockerfile ! 
https://github.com/Sinamecc/sinamecc-wui/blob/SIN-I13/Dockerfile

2024-12-12 14:41 UTC, naybort approved these changes

2024-12-12 15:40 UTC, Izcarmt95 approved these changes

2024-12-12 15:43 UTC, merged